# Generated by Django 4.0 on 2021-12-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_topic_of_article_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.article')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Topic_of_article',
        ),
        migrations.AddField(
            model_name='position',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.topic'),
        ),
    ]
