# Generated by Django 4.0 on 2021-12-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_position_remove_topic_topics_delete_topic_of_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='default title', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
